export enum MethodType {
  BlogEntry_Comments = "blogEntry.comments",
  BlogEntry_View = "blogEntry.view",
  Contest_Hacks = "contest.hacks",
  Contest_List = "contest.list",
  Contest_RatingChanges = "contest.ratingChanges",
  Contest_Standings = "contest.standings",
  Contest_Status = "contest.status",
  Problemset_Problems = "problemset.problems",
  Problemset_RecentStatus = "problemset.recentStatus",
  RecentActions = "recentActions",
  User_BlogEntries = "user.blogEntries",
  User_Friends = "user.friends",
  User_Info = "user.info",
  User_RatedList = "user.ratedList",
  User_Rating = "user.rating",
  User_Status = "user.status",
}
